### ISSUE TITLE
Github warning

### ISSUE THREAD

**Issue by bojidar-bg** [VanessaE/hdx-16#3]
In github, "Sorry, we had to truncate this directory to 1,000 files. 2,027 entries were omitted from the list." appears on top of the list of textures. Maybe you should rearrange the textures into directories? :smile:

**Comment by VanessaE** [comment]
Not possible to do, unfortunately.  Minetest (the game the texture pack is for) does not, as far as I am aware, allow textures in a texture pack to be sorted into sub-directories.  They all have to be in one directory.

**Comment by bojidar-bg** [comment]
Maybe you can create some simple (bash?) script that will collect all the textures from different folders into the root folder? :smiley:

**Comment by VanessaE** [comment]
I could easily do that, but the problem is that too many people who would download this texture pack either don't know how to run a bash script, or can't :stuck_out_tongue_closed_eyes:

**Comment by bojidar-bg** [comment]
xD, well that rules out all other possibilities as well... (except politely asking the minetest team to change the texture pack format...)

**Comment by VanessaE** [comment]
Heh. Actually I did raise the question in the developers' channel but no response as yet.  May need to file an issue against the main repo or something.
